Adding check to see if upload succeeded.

diff --git a/.github/workflows/upload_sop.yml b/.github/workflows/upload_sop.yml
--- a/.github/workflows/upload_sop.yml
+++ b/.github/workflows/upload_sop.yml
@@ -66,3 +66,11 @@ jobs:
           QUALER_PASSWORD: ${{ secrets.QUALER_PASSWORD }}
           SOP_ID: 2351
           MERGED_FILE: ${{ env.MERGED_FILE }}
+
+      - name: Check Upload Status
+        if: env.skip != 'true'
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "❌ Error: Upload to Qualer failed."
+            exit 1
+          fi
